[package]
name = "rynixc"
description = "The Rynix compiler driver (CLI)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rynix-span = { workspace = true }
rynix-diag = { workspace = true }
rynix-lexer = { workspace = true }
rynix-ast = { workspace = true }
rynix-parser = { workspace = true }
rynix-sema = { workspace = true }
rynix-rir = { workspace = true }
rynix-codegen = { workspace = true }
serde_json = { workspace = true }
semver = { workspace = true }

[lints]
workspace = true
