[package]
name = "rynix-rir"
description = "Canonical SSA IR (RIR) for Rynix (Phase 5)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rynix-span = { workspace = true }
rynix-diag = { workspace = true }
rynix-ast = { workspace = true }
rynix-sema = { workspace = true }
rustc-hash = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
rynix-parser = { workspace = true }
insta = { workspace = true }

[lints]
workspace = true
