[package]
name = "rynix-codegen"
description = "Textual LLVM IR emission from RIR (Phase 7)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rynix-span = { workspace = true }
rynix-rir = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
rynix-ast = { workspace = true }
rynix-diag = { workspace = true }
rynix-parser = { workspace = true }
rynix-sema = { workspace = true }
insta = { workspace = true }

[lints]
workspace = true
